version: "2"

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/joelanford/orb)

linters:
  enable:
    - errcheck
    - errorlint
    - gocritic
    - importas
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

  settings:
    errcheck:
      check-type-assertions: false
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - os.RemoveAll
    errorlint:
      asserts: true
      errorf: false
    gocritic:
      enabled-tags:
        - diagnostic
    importas:
      no-unaliased: true
      alias:
        - pkg: github.com/blang/semver/v4
          alias: bsemver
        - pkg: github.com/Masterminds/semver/v3
          alias: mmsemver

  exclusions:
    paths:
      - internal/termimage/internal/rasterx
      - internal/termimage/internal/oksvg
    rules:
      - linters: [errcheck]
        text: "Error return value of `.*\\.Close` is not checked"
