name: Image

on:
  push:
    branches: [main]

permissions:
  packages: write

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build snapshot image
        run: make release
      - name: Push latest image
        run: |
          docker push ghcr.io/joelanford/orb:latest-amd64
          docker push ghcr.io/joelanford/orb:latest-arm64
          docker manifest create ghcr.io/joelanford/orb:latest \
            ghcr.io/joelanford/orb:latest-amd64 \
            ghcr.io/joelanford/orb:latest-arm64
          docker manifest push ghcr.io/joelanford/orb:latest
